#!/bin/bash

: ${DOCKER_USER:? required}

GO111MODULE=off CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o webhook-pro
docker build --no-cache -t ${DOCKER_USER}/webhook-pro:v1 .
rm -rf webhook-pro
docker push ${DOCKER_USER}/webhook-pro:v1
